name: JimColumbus
favicon: null
layout_spectrum: 0.7389234977308661
typography_spectrum: 0.8583765323273838
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5768766836263239
  lightness: 0.2703999159857631
  saturation: 0.21364427544176579
  rhythmicContrast: 0.9730393020436168
purpose: []
